### ISSUE TITLE
Api connection error

### ISSUE THREAD

**Issue by ondravirag** [PUQ-sp-z-o-o/PUQ_WHMCS-Public-Synology#1]
Hi, I have a problem with the module in whmcs writes that it is not possible to connect to the api. But if it's not because I have a DSM 7+ version

Couldn't it be done for this version of DSM?
to fix it somehow?

Thank you

**Comment by puqcloud** [comment]
Synology DSM 7 is beta.
As soon as a stable version appears, we will try to complete the module.
Probably different API.

We are starting to work on this.

**Comment by ondravirag** [comment]
There is a different arrangement of api positions, I have already modified the login in the code:

in puqPublicSynology.php
line 50
/webapi/auth.cgi?api=SYNO.API.Auth&version=3&method=login&account=


I'll look at other api urls for creation and administration and I'll write anyway.

**Comment by ondravirag** [comment]
**It seems that everything works as it should on DSM version 7. Unfortunately, the creation of the user does not work, it is the only snag.**

**Comment by puqcloud** [comment]
Now works DSM6 and DSM7
